/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosProyecto;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;




/**
 *
 * @author Usuario
 */
public class frmCulturasdinamicas extends javax.swing.JFrame {
    public int a1,a2,a3,a4,a5,a6,a7;
    public  static int Promedio;
    public static String tiempototal="";
    int lapsoTiempo=0;
    int segundos=0;
    int minutos=0;
    int horas=0;
    boolean start=false;
    int sig=0;
   
    
    
    
    String sec=String.format("%02d",segundos);
    String min=String.format("%02d",minutos);
    String hor=String.format("%02d",horas);
    
    Timer tiempo=new Timer(1000,new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        lapsoTiempo=lapsoTiempo +1000;
        horas=(lapsoTiempo/3600000);
        minutos=(lapsoTiempo/60000)%60;
        segundos=(lapsoTiempo/1000)%60;
        String sec=String.format("%02d",segundos);
        String min=String.format("%02d",minutos);
        String hor=String.format("%02d",horas);
        
        //lblCronometro.setText(hor+":"+min+":"+sec);
        //tiempototal=lblCronometro.getText();
        txttmpo.setText("\n"+"   "+hor+":"+min+":"+sec);
        tiempototal=txttmpo.getText();
        
        
        }
    });
    
 
    /**
     * Creates new form frmCulturasdinamicas
     */
    public frmCulturasdinamicas() {
        initComponents();
        this.setLocationRelativeTo(null);
        lblSimbolo.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
        lblSimbolo1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
        lblSimbolo2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
        lblSimbolo3.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
        lblSimbolo4.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
        lblSimbolo5.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
        lblSimbolo6.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
        tiempo.start();
        
        
        
    }
     
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblImagenToltecas = new javax.swing.JLabel();
        lblImagenZapotecas = new javax.swing.JLabel();
        lblImagenAzteca = new javax.swing.JLabel();
        lblImagenMaya = new javax.swing.JLabel();
        lblImagenMixteca = new javax.swing.JLabel();
        lblImagenOlmeca = new javax.swing.JLabel();
        lblImagenTeotihuacanos = new javax.swing.JLabel();
        lblOlmecas = new javax.swing.JLabel();
        lblAztecas = new javax.swing.JLabel();
        lblMixtecos = new javax.swing.JLabel();
        lblTeotihuacanos = new javax.swing.JLabel();
        lblZapotecos = new javax.swing.JLabel();
        lblToltecas = new javax.swing.JLabel();
        lblmayas = new javax.swing.JLabel();
        lbltoltecasc = new javax.swing.JLabel();
        lblOlmecasc = new javax.swing.JLabel();
        lblAztecasc = new javax.swing.JLabel();
        lblZapotecosc = new javax.swing.JLabel();
        lblTeotihuacanosc = new javax.swing.JLabel();
        lblMixtecosc = new javax.swing.JLabel();
        lblMAyac = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        lblSimbolo6 = new javax.swing.JLabel();
        lblSimbolo5 = new javax.swing.JLabel();
        lblSimbolo4 = new javax.swing.JLabel();
        lblSimbolo3 = new javax.swing.JLabel();
        lblSimbolo2 = new javax.swing.JLabel();
        lblSimbolo1 = new javax.swing.JLabel();
        lblSimbolo = new javax.swing.JLabel();
        btnAceptarcontinuar = new javax.swing.JButton();
        txttmpo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mhMayas = new javax.swing.JTextField();
        mhOlmecas = new javax.swing.JTextField();
        mhAztecas = new javax.swing.JTextField();
        mhMixtecos = new javax.swing.JTextField();
        mhTeotihuacanos = new javax.swing.JTextField();
        mhZapotecos = new javax.swing.JTextField();
        mhToltecas = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MEMORAMA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        lblImagenToltecas.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenToltecas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblImagenToltecas.setForeground(new java.awt.Color(255, 0, 0));
        lblImagenToltecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/Toltecas.jpg"))); // NOI18N
        lblImagenToltecas.setToolTipText("Su principal centro ceremonial fue Tolla-Xicocotlitan  y su principal dios Quetzalcoatl");
        lblImagenToltecas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblImagenToltecasMouseDragged(evt);
            }
        });
        jPanel1.add(lblImagenToltecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 110, 90));

        lblImagenZapotecas.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenZapotecas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblImagenZapotecas.setForeground(new java.awt.Color(255, 0, 0));
        lblImagenZapotecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/Zapotecas.jpg"))); // NOI18N
        lblImagenZapotecas.setToolTipText("Su principal centro ceremonial fue Monte Alban  y su principal dios Xipe Totec");
        lblImagenZapotecas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblImagenZapotecasMouseDragged(evt);
            }
        });
        jPanel1.add(lblImagenZapotecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 370, 110, 90));

        lblImagenAzteca.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenAzteca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblImagenAzteca.setForeground(new java.awt.Color(255, 0, 0));
        lblImagenAzteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/Aztecas.jpg"))); // NOI18N
        lblImagenAzteca.setToolTipText("Su principal centro ceremonial fue el Templo mayor  y su principal dios Huitzillopochtli");
        lblImagenAzteca.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblImagenAztecaMouseDragged(evt);
            }
        });
        jPanel1.add(lblImagenAzteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 110, 90));

        lblImagenMaya.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenMaya.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblImagenMaya.setForeground(new java.awt.Color(255, 0, 0));
        lblImagenMaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/Mayas.jpg"))); // NOI18N
        lblImagenMaya.setToolTipText("Su principal centro ceremonial fue Chichen Itza  y su principal dios Kukulcan");
        lblImagenMaya.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblImagenMayaMouseDragged(evt);
            }
        });
        jPanel1.add(lblImagenMaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 110, 90));

        lblImagenMixteca.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenMixteca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblImagenMixteca.setForeground(new java.awt.Color(255, 0, 0));
        lblImagenMixteca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/Mixtecos.jpg"))); // NOI18N
        lblImagenMixteca.setToolTipText("Su principal centro ceremonial fue Mitla \ny su principal dios Dzahui");
        lblImagenMixteca.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblImagenMixtecaMouseDragged(evt);
            }
        });
        jPanel1.add(lblImagenMixteca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 110, 90));

        lblImagenOlmeca.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenOlmeca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblImagenOlmeca.setForeground(new java.awt.Color(255, 0, 0));
        lblImagenOlmeca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/Olmecas.jpg"))); // NOI18N
        lblImagenOlmeca.setToolTipText("Su principal centro ceremonial fue Tres zapotes\ny su principal dios Jaguar(Nahual)");
        lblImagenOlmeca.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblImagenOlmecaMouseDragged(evt);
            }
        });
        jPanel1.add(lblImagenOlmeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 110, 90));

        lblImagenTeotihuacanos.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenTeotihuacanos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblImagenTeotihuacanos.setForeground(new java.awt.Color(255, 0, 0));
        lblImagenTeotihuacanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/Teotihuacanos.jpg"))); // NOI18N
        lblImagenTeotihuacanos.setToolTipText("Su principal centro historico fue Teotihuacan\ny su principal dios fue Quetzalcoatl");
        lblImagenTeotihuacanos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblImagenTeotihuacanosMouseDragged(evt);
            }
        });
        jPanel1.add(lblImagenTeotihuacanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 110, 90));

        lblOlmecas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblOlmecas.setForeground(new java.awt.Color(255, 255, 255));
        lblOlmecas.setText("Olmecas");
        jPanel1.add(lblOlmecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, -1, -1));

        lblAztecas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblAztecas.setForeground(new java.awt.Color(255, 255, 255));
        lblAztecas.setText("Aztecas");
        jPanel1.add(lblAztecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        lblMixtecos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblMixtecos.setForeground(new java.awt.Color(255, 255, 255));
        lblMixtecos.setText("Mixtecos");
        jPanel1.add(lblMixtecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        lblTeotihuacanos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblTeotihuacanos.setForeground(new java.awt.Color(255, 255, 255));
        lblTeotihuacanos.setText("Teotihuacanos");
        jPanel1.add(lblTeotihuacanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        lblZapotecos.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblZapotecos.setForeground(new java.awt.Color(255, 255, 255));
        lblZapotecos.setText("Zapotecos");
        jPanel1.add(lblZapotecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, -1));

        lblToltecas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblToltecas.setForeground(new java.awt.Color(255, 255, 255));
        lblToltecas.setText("Toltecas");
        jPanel1.add(lblToltecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, -1, -1));

        lblmayas.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        lblmayas.setForeground(new java.awt.Color(255, 255, 255));
        lblmayas.setText("Mayas");
        jPanel1.add(lblmayas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        lbltoltecasc.setBackground(new java.awt.Color(255, 255, 255));
        lbltoltecasc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbltoltecasc.setForeground(new java.awt.Color(255, 0, 0));
        lbltoltecasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/recuadrosV.png"))); // NOI18N
        lbltoltecasc.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lbltoltecasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 140, 120));

        lblOlmecasc.setBackground(new java.awt.Color(255, 255, 255));
        lblOlmecasc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblOlmecasc.setForeground(new java.awt.Color(255, 0, 0));
        lblOlmecasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/recuadrosV.png"))); // NOI18N
        lblOlmecasc.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lblOlmecasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 140, 120));

        lblAztecasc.setBackground(new java.awt.Color(255, 255, 255));
        lblAztecasc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblAztecasc.setForeground(new java.awt.Color(255, 0, 0));
        lblAztecasc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/recuadrosV.png"))); // NOI18N
        lblAztecasc.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lblAztecasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 140, 120));

        lblZapotecosc.setBackground(new java.awt.Color(255, 255, 255));
        lblZapotecosc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblZapotecosc.setForeground(new java.awt.Color(255, 0, 0));
        lblZapotecosc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/recuadrosV.png"))); // NOI18N
        lblZapotecosc.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lblZapotecosc, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 140, 120));

        lblTeotihuacanosc.setBackground(new java.awt.Color(255, 255, 255));
        lblTeotihuacanosc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblTeotihuacanosc.setForeground(new java.awt.Color(255, 0, 0));
        lblTeotihuacanosc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/recuadrosV.png"))); // NOI18N
        lblTeotihuacanosc.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lblTeotihuacanosc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 140, 120));

        lblMixtecosc.setBackground(new java.awt.Color(255, 255, 255));
        lblMixtecosc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMixtecosc.setForeground(new java.awt.Color(255, 0, 0));
        lblMixtecosc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/recuadrosV.png"))); // NOI18N
        lblMixtecosc.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lblMixtecosc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 140, 120));

        lblMAyac.setBackground(new java.awt.Color(0, 0, 0));
        lblMAyac.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblMAyac.setForeground(new java.awt.Color(255, 0, 0));
        lblMAyac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeCulturadinamica/recuadrosV.png"))); // NOI18N
        lblMAyac.setText(" ");
        lblMAyac.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.add(lblMAyac, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, 120));

        btnSalir1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.blue, java.awt.Color.blue));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 50, 20));
        jPanel1.add(lblSimbolo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 25, 25));
        jPanel1.add(lblSimbolo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 25, 25));
        jPanel1.add(lblSimbolo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 25, 25));
        jPanel1.add(lblSimbolo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, 25, 25));
        jPanel1.add(lblSimbolo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, 25, 25));
        jPanel1.add(lblSimbolo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 25, 25));
        jPanel1.add(lblSimbolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 25, 25));

        btnAceptarcontinuar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnAceptarcontinuar.setText("Aceptar/Continuar");
        btnAceptarcontinuar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.blue, java.awt.Color.blue));
        btnAceptarcontinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarcontinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptarcontinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 130, 20));

        txttmpo.setBackground(new java.awt.Color(0, 0, 51));
        txttmpo.setFont(new java.awt.Font("Arial Black", 2, 14)); // NOI18N
        txttmpo.setForeground(new java.awt.Color(255, 255, 255));
        txttmpo.setText("    00:00:00");
        txttmpo.setBorder(null);
        txttmpo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttmpoActionPerformed(evt);
            }
        });
        jPanel1.add(txttmpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 34));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TIEMPO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));
        jPanel1.add(mhMayas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, 120));

        mhOlmecas.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(mhOlmecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 140, 120));
        jPanel1.add(mhAztecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 140, 120));
        jPanel1.add(mhMixtecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 140, 120));
        jPanel1.add(mhTeotihuacanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 140, 120));
        jPanel1.add(mhZapotecos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 140, 120));
        jPanel1.add(mhToltecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 140, 120));

        jLabel8.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ARRASTRE CADA IMAGEN A SU CULTURA CORRESPONDIENTE  ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Culturas-Dinamicas.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 800, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        JOptionPane.showMessageDialog(null,"Todo su progreso sera eliminado","Aviso salida", 2);
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void lblImagenAztecaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenAztecaMouseDragged
        // TODO add your handling code here:
        lblImagenAzteca.setLocation(lblImagenAzteca.getLocation().x+evt.getX()-lblImagenAzteca.getWidth()/2,
                lblImagenAzteca.getLocation().y+evt.getY()-lblImagenAzteca.getHeight());
        int x1=lblImagenAzteca.getX();
        int y1=lblImagenAzteca.getY();
        if ((x1>=454 && x1<=474) &&(y1>=95 && y1<=116))
        {
            lblSimbolo2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton correcto.png"));
            a3=1; 
            mhAztecas.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(null,"Sabias que los Aztecas mas pobres solian realizar \n"
                                             + "una especie de sobres de maiz los cuales se les llamaba\n"
                                             + "Tamales y que los rellenaban con insectos o animales que \n"
                                             + "pudieran servir como alimento "," Cultura Azteca",1);
            
            
            
            
        }
        else 
        {
            lblSimbolo2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
            a3=0;
            
            
        }     
    }//GEN-LAST:event_lblImagenAztecaMouseDragged

    private void lblImagenMayaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMayaMouseDragged
        // TODO add your handling code here:
        lblImagenMaya.setLocation(lblImagenMaya.getLocation().x+evt.getX()-lblImagenMaya.getWidth()/2,
                lblImagenMaya.getLocation().y+evt.getY()-lblImagenMaya.getHeight());
        int x1=lblImagenMaya.getX();
        int y1=lblImagenMaya.getY();
        
        
        if ((x1>=134 && x1<=154) &&(y1>=95 && y1<=116))
        {
            lblSimbolo.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton correcto.png"));
            a1=1;
            mhMayas.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(null,"Sabias que los Mayas fueron astrologos muy \n"
                                             + "precisos que estudiaron varios fenomenos celestes y\n"
                                             + "su calendario es mas exacto que el calendario gregoriano"," Cultura Maya",1);
            
                         
        }
        else 
        {
            lblSimbolo.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
            a1=0;
            
        }
      
        
       
    }//GEN-LAST:event_lblImagenMayaMouseDragged

    private void lblImagenMixtecaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenMixtecaMouseDragged
        // TODO add your handling code here:
        lblImagenMixteca.setLocation(lblImagenMixteca.getLocation().x+evt.getX()-lblImagenMixteca.getWidth()/2,
                lblImagenMixteca.getLocation().y+evt.getY()-lblImagenMixteca.getHeight());
        int x1=lblImagenMixteca.getX();
        int y1=lblImagenMixteca.getY();
        
        
        if ((x1>=614 && x1<=634) &&(y1>=95 && y1<=116))
        {
            mhMixtecos.setBackground(Color.GREEN);
            lblSimbolo3.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton correcto.png"));
            a4=1;
            JOptionPane.showMessageDialog(null,"Sabias que los Mixtecos fueron reconocidos por\n"
                                             + "su gran desarrollo militar y por mantener vinculos\n"
                                             + "estrategicos para resistir la invasion Azteca"," Cultura Mixteca",1);
                  
        }
        else 
        {
            lblSimbolo3.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
            a4=0;
        }
        
    }//GEN-LAST:event_lblImagenMixtecaMouseDragged

    private void lblImagenOlmecaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenOlmecaMouseDragged
        // TODO add your handling code here:
         lblImagenOlmeca.setLocation(lblImagenOlmeca.getLocation().x+evt.getX()-lblImagenOlmeca.getWidth()/2,
                lblImagenOlmeca.getLocation().y+evt.getY()-lblImagenOlmeca.getHeight());
      int x1=lblImagenOlmeca.getX();
        int y1=lblImagenOlmeca.getY();
        
        
        if ((x1>=294 && x1<=314) &&(y1>=95 && y1<=116))
        {
            mhOlmecas.setBackground(Color.GREEN);
            lblSimbolo1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton correcto.png"));
            a2=1;
            JOptionPane.showMessageDialog(null,"Sabias que a la Cultura Olmeca se le atribuye el\n"
                                             + "Juego de pelota Mesoamericano o juego de bola con\n"
                                             + "fines religiosos"," Cultura Olmeca",1);
            
        }
        else 
        {
            lblSimbolo1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
            a2=0;
        }
        
      
    }//GEN-LAST:event_lblImagenOlmecaMouseDragged

    private void lblImagenTeotihuacanosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenTeotihuacanosMouseDragged
        // TODO add your handling code here:
         lblImagenTeotihuacanos.setLocation(lblImagenTeotihuacanos.getLocation().x+evt.getX()-lblImagenTeotihuacanos.getWidth()/2,
                lblImagenTeotihuacanos.getLocation().y+evt.getY()-lblImagenTeotihuacanos.getHeight());
         int x1=lblImagenTeotihuacanos.getX();
        int y1=lblImagenTeotihuacanos.getY();
        
        
        if ((x1>=214 && x1<=234) &&(y1>=255 && y1<=276))
        {
            lblSimbolo4.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton correcto.png"));
            a5=1;
            mhTeotihuacanos.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(null,"Sabias que a la Cultura Teotihucacana fue declarada \n"
                                             + "bien Mixto por su valor natural e historico, pues aqui  \n"
                                             + "se dio la primera domesticacion de maiz","Cultura Teotihuacana",1);
               
        }
        else 
        {
            lblSimbolo4.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
            a5=0;
        }
        
    }//GEN-LAST:event_lblImagenTeotihuacanosMouseDragged

    private void lblImagenToltecasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenToltecasMouseDragged
        // TODO add your handling code here:
        lblImagenToltecas.setLocation(lblImagenToltecas.getLocation().x+evt.getX()-lblImagenToltecas.getWidth()/2,
                lblImagenToltecas.getLocation().y+evt.getY()-lblImagenToltecas.getHeight());
        int x1=lblImagenToltecas.getX();
        int y1=lblImagenToltecas.getY();
       
        
        if ((x1>=534 && x1<=554) &&(y1>=255 && y1<=276))
        {
           lblSimbolo6.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton correcto.png"));
           a7=1;
           mhToltecas.setBackground(Color.GREEN); 
           JOptionPane.showMessageDialog(null,"Sabias que los Toltecas fueron guerreros religiosos\n"
                                             + "que diifundieron el culto de su dios Quetzalcoatl\n"
                                             ," Cultura Tolteca",1);
            
        }
        else 
        {
            lblSimbolo6.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
          a7=0;
        }
        
    }//GEN-LAST:event_lblImagenToltecasMouseDragged

    private void lblImagenZapotecasMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagenZapotecasMouseDragged
        // TODO add your handling code here:
         lblImagenZapotecas.setLocation(lblImagenZapotecas.getLocation().x+evt.getX()-lblImagenZapotecas.getWidth()/2,
                lblImagenZapotecas.getLocation().y+evt.getY()-lblImagenZapotecas.getHeight());
         int x1=lblImagenZapotecas.getX();
        int y1=lblImagenZapotecas.getY();
       
        
        if ((x1>=374 && x1<=394) &&(y1>=255 && y1<=276))
        {
            lblSimbolo5.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton correcto.png"));
            a6=1;
            mhZapotecos.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(null,"Sabias que los Zapotecas adoraban a sus antepasados\n"
                                             + "y creyendo en un mundo paradisiaco,desarrollaban el\n"
                                             + "culto a los muertos"," Cultura Zapoteca",1);
                
        }
        else 
        {
            lblSimbolo5.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesdeCulturadinamica\\Boton incorrecto.png"));
            a6=0;
            
        }
       
    }//GEN-LAST:event_lblImagenZapotecasMouseDragged

    private void btnAceptarcontinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarcontinuarActionPerformed
        // TODO add your handling code here:
         int puntos =a1+a2+a3+a4+a5+a6+a7;
         Promedio=puntos;
         if(puntos==7)
         {
        frmExamen verfrmExamen= new frmExamen();
        verfrmExamen.setVisible(true);
        this.hide();   
         }  
    }//GEN-LAST:event_btnAceptarcontinuarActionPerformed

    private void txttmpoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttmpoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txttmpoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCulturasdinamicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCulturasdinamicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCulturasdinamicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCulturasdinamicas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCulturasdinamicas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarcontinuar;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAztecas;
    private javax.swing.JLabel lblAztecasc;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblImagenAzteca;
    private javax.swing.JLabel lblImagenMaya;
    private javax.swing.JLabel lblImagenMixteca;
    private javax.swing.JLabel lblImagenOlmeca;
    private javax.swing.JLabel lblImagenTeotihuacanos;
    private javax.swing.JLabel lblImagenToltecas;
    private javax.swing.JLabel lblImagenZapotecas;
    private javax.swing.JLabel lblMAyac;
    private javax.swing.JLabel lblMixtecos;
    private javax.swing.JLabel lblMixtecosc;
    private javax.swing.JLabel lblOlmecas;
    private javax.swing.JLabel lblOlmecasc;
    private javax.swing.JLabel lblSimbolo;
    private javax.swing.JLabel lblSimbolo1;
    private javax.swing.JLabel lblSimbolo2;
    private javax.swing.JLabel lblSimbolo3;
    private javax.swing.JLabel lblSimbolo4;
    private javax.swing.JLabel lblSimbolo5;
    private javax.swing.JLabel lblSimbolo6;
    private javax.swing.JLabel lblTeotihuacanos;
    private javax.swing.JLabel lblTeotihuacanosc;
    private javax.swing.JLabel lblToltecas;
    private javax.swing.JLabel lblZapotecos;
    private javax.swing.JLabel lblZapotecosc;
    private javax.swing.JLabel lblmayas;
    private javax.swing.JLabel lbltoltecasc;
    private javax.swing.JTextField mhAztecas;
    private javax.swing.JTextField mhMayas;
    private javax.swing.JTextField mhMixtecos;
    private javax.swing.JTextField mhOlmecas;
    private javax.swing.JTextField mhTeotihuacanos;
    private javax.swing.JTextField mhToltecas;
    private javax.swing.JTextField mhZapotecos;
    private javax.swing.JTextField txttmpo;
    // End of variables declaration//GEN-END:variables
}
