/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosProyecto;

import static formulariosProyecto.frmExamen.Promedio;
import static formulariosProyecto.frmExamen.total;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frmExamenDinamicoGenerado extends javax.swing.JFrame {
    frmDatosalumno datosuperior=new frmDatosalumno();
    frmExamenDinamico datosrecuperados=new frmExamenDinamico();
    public static int preguntas,incisos,punto1=0,punto2=0,punto3=0,punto4=0,punto5=0,punto6=0,punto7=0,punto8=0,punto9=0,punto10=0;
    public static int total;
     public static float Promedio,totalAciertos=0;
     
    
    

    /**
     * Creates new form frmExamenDinamico
     */
    public frmExamenDinamicoGenerado() {
        initComponents();
        this.setLocationRelativeTo(null);
        frmDatosdocente datosente =new frmDatosdocente();
        lblEscuela.setText(datosuperior.Escuela);
        lblGradoyGrupo.setText(datosuperior.GrupoyGrado);
        lblMateria.setText(datosente.Materia);
        lblNombreDocente.setText(datosente.NombreDocente);
        lblAlumno.setText(datosuperior.Nombre);
        lblPregunta1.setText("1.-"+datosrecuperados.p1[0]);chboxA1.setText("a) "+datosrecuperados.p1[1]);chboxB1.setText("b) "+datosrecuperados.p1[2]);chboxC1.setText("c) "+datosrecuperados.p1[3]);
        lblPregunta2.setText("2.-"+datosrecuperados.p2[0]);chboxA2.setText("a) "+datosrecuperados.p2[1]);chboxB2.setText("b) "+datosrecuperados.p2[2]);chboxC2.setText("c) "+datosrecuperados.p2[3]);
        lblPregunta3.setText("3.-"+datosrecuperados.p3[0]);chboxA3.setText("a) "+datosrecuperados.p3[1]);chboxB3.setText("b) "+datosrecuperados.p3[2]);chboxC3.setText("c) "+datosrecuperados.p3[3]);
        lblPregunta4.setText("4.-"+datosrecuperados.p4[0]);chboxA4.setText("a) "+datosrecuperados.p4[1]);chboxB4.setText("b) "+datosrecuperados.p4[2]);chboxC4.setText("c) "+datosrecuperados.p4[3]);
        lblPregunta5.setText("5.-"+datosrecuperados.p5[0]);chboxA5.setText("a) "+datosrecuperados.p5[1]);chboxB5.setText("b) "+datosrecuperados.p5[2]);chboxC5.setText("c) "+datosrecuperados.p5[3]);
        lblPregunta6.setText("6.-"+datosrecuperados.p6[0]);chboxA6.setText("a) "+datosrecuperados.p6[1]);chboxB6.setText("b) "+datosrecuperados.p6[2]);chboxC6.setText("c) "+datosrecuperados.p6[3]);
        lblPregunta7.setText("7.-"+datosrecuperados.p7[0]);chboxA7.setText("a) "+datosrecuperados.p7[1]);chboxB7.setText("b) "+datosrecuperados.p7[2]);chboxC7.setText("c) "+datosrecuperados.p7[3]);
        lblPregunta8.setText("8.-"+datosrecuperados.p8[0]);chboxA8.setText("a) "+datosrecuperados.p8[1]);chboxB8.setText("b) "+datosrecuperados.p8[2]);chboxC8.setText("c) "+datosrecuperados.p8[3]);
        lblPregunta9.setText("9.-"+datosrecuperados.p9[0]);chboxA9.setText("a) "+datosrecuperados.p9[1]);chboxB9.setText("b) "+datosrecuperados.p9[2]);chboxC9.setText("c) "+datosrecuperados.p9[3]);
        lblPregunta10.setText("10.-"+datosrecuperados.p10[0]);chboxA10.setText("a) "+datosrecuperados.p10[1]);chboxB10.setText("b) "+datosrecuperados.p10[2]);chboxC10.setText("c) "+datosrecuperados.p10[3]);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        buttonGroup13 = new javax.swing.ButtonGroup();
        buttonGroup14 = new javax.swing.ButtonGroup();
        buttonGroup15 = new javax.swing.ButtonGroup();
        buttonGroup16 = new javax.swing.ButtonGroup();
        buttonGroup17 = new javax.swing.ButtonGroup();
        buttonGroup18 = new javax.swing.ButtonGroup();
        buttonGroup19 = new javax.swing.ButtonGroup();
        buttonGroup20 = new javax.swing.ButtonGroup();
        buttonGroup21 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEscuela = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        lblNombreDocente = new javax.swing.JLabel();
        lblMateria = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnFinalizar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        chboxA1 = new javax.swing.JRadioButton();
        chboxB1 = new javax.swing.JRadioButton();
        chboxC1 = new javax.swing.JRadioButton();
        lblPregunta1 = new javax.swing.JLabel();
        lblPregunta2 = new javax.swing.JLabel();
        chboxA2 = new javax.swing.JRadioButton();
        chboxB2 = new javax.swing.JRadioButton();
        chboxC2 = new javax.swing.JRadioButton();
        lblPregunta3 = new javax.swing.JLabel();
        chboxA3 = new javax.swing.JRadioButton();
        chboxB3 = new javax.swing.JRadioButton();
        chboxC3 = new javax.swing.JRadioButton();
        chboxC4 = new javax.swing.JRadioButton();
        chboxA4 = new javax.swing.JRadioButton();
        lblPregunta4 = new javax.swing.JLabel();
        chboxB4 = new javax.swing.JRadioButton();
        lblPregunta5 = new javax.swing.JLabel();
        chboxA5 = new javax.swing.JRadioButton();
        chboxC5 = new javax.swing.JRadioButton();
        chboxB5 = new javax.swing.JRadioButton();
        lblPregunta6 = new javax.swing.JLabel();
        chboxA6 = new javax.swing.JRadioButton();
        chboxB6 = new javax.swing.JRadioButton();
        chboxC6 = new javax.swing.JRadioButton();
        lblPregunta7 = new javax.swing.JLabel();
        chboxA7 = new javax.swing.JRadioButton();
        chboxB7 = new javax.swing.JRadioButton();
        chboxC7 = new javax.swing.JRadioButton();
        lblPregunta8 = new javax.swing.JLabel();
        chboxA8 = new javax.swing.JRadioButton();
        chboxB8 = new javax.swing.JRadioButton();
        chboxC8 = new javax.swing.JRadioButton();
        lblPregunta9 = new javax.swing.JLabel();
        chboxA9 = new javax.swing.JRadioButton();
        chboxB9 = new javax.swing.JRadioButton();
        chboxC9 = new javax.swing.JRadioButton();
        lblPregunta10 = new javax.swing.JLabel();
        chboxA10 = new javax.swing.JRadioButton();
        chboxB10 = new javax.swing.JRadioButton();
        chboxC10 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        lblGradoyGrupo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel1.setText("Nombre del docente:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel2.setText("Materia:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel3.setText("Nombre del alumno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel4.setText("Escuela:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        lblEscuela.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jPanel1.add(lblEscuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 150, 18));

        lblAlumno.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jPanel1.add(lblAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 250, 18));

        lblNombreDocente.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jPanel1.add(lblNombreDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 183, 18));

        lblMateria.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jPanel1.add(lblMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 60, 130, 18));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 580, -1));

        btnFinalizar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnFinalizar.setText("Finalizar examen");
        btnFinalizar.setBorder(new javax.swing.border.MatteBorder(null));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 656, 140, 20));

        btnAtras.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setBorder(new javax.swing.border.MatteBorder(null));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 656, 50, 20));

        buttonGroup1.add(chboxA1);
        jPanel1.add(chboxA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        buttonGroup1.add(chboxB1);
        jPanel1.add(chboxB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        buttonGroup1.add(chboxC1);
        jPanel1.add(chboxC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, -1, -1));

        lblPregunta1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta1.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 440, 23));

        lblPregunta2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta2.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 440, 23));

        buttonGroup2.add(chboxA2);
        jPanel1.add(chboxA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        buttonGroup2.add(chboxB2);
        jPanel1.add(chboxB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        buttonGroup2.add(chboxC2);
        jPanel1.add(chboxC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        lblPregunta3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta3.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 440, 23));

        buttonGroup3.add(chboxA3);
        jPanel1.add(chboxA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        buttonGroup3.add(chboxB3);
        jPanel1.add(chboxB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));

        buttonGroup3.add(chboxC3);
        jPanel1.add(chboxC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        buttonGroup4.add(chboxC4);
        jPanel1.add(chboxC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, -1, -1));

        buttonGroup4.add(chboxA4);
        jPanel1.add(chboxA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        lblPregunta4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta4.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 440, 23));

        buttonGroup4.add(chboxB4);
        jPanel1.add(chboxB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        lblPregunta5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta5.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 440, 23));

        buttonGroup5.add(chboxA5);
        jPanel1.add(chboxA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        buttonGroup5.add(chboxC5);
        jPanel1.add(chboxC5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, -1, -1));

        buttonGroup5.add(chboxB5);
        jPanel1.add(chboxB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, -1, -1));

        lblPregunta6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta6.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 440, 23));

        buttonGroup6.add(chboxA6);
        jPanel1.add(chboxA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        buttonGroup6.add(chboxB6);
        jPanel1.add(chboxB6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, -1, -1));

        buttonGroup6.add(chboxC6);
        jPanel1.add(chboxC6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, -1));

        lblPregunta7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta7.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 440, 23));

        buttonGroup7.add(chboxA7);
        jPanel1.add(chboxA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        buttonGroup7.add(chboxB7);
        jPanel1.add(chboxB7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 460, -1, -1));

        buttonGroup7.add(chboxC7);
        jPanel1.add(chboxC7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        lblPregunta8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta8.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 440, 23));

        buttonGroup8.add(chboxA8);
        jPanel1.add(chboxA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, -1, -1));

        buttonGroup8.add(chboxB8);
        jPanel1.add(chboxB8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        buttonGroup8.add(chboxC8);
        jPanel1.add(chboxC8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, -1, -1));

        lblPregunta9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta9.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 440, 23));

        buttonGroup9.add(chboxA9);
        jPanel1.add(chboxA9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, -1, -1));

        buttonGroup9.add(chboxB9);
        jPanel1.add(chboxB9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 560, -1, -1));

        buttonGroup9.add(chboxC9);
        jPanel1.add(chboxC9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        lblPregunta10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPregunta10.setText("Introduzca su pregunta");
        jPanel1.add(lblPregunta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, 440, 23));

        buttonGroup10.add(chboxA10);
        jPanel1.add(chboxA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, -1, -1));

        buttonGroup10.add(chboxB10);
        jPanel1.add(chboxB10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 610, -1, -1));

        buttonGroup10.add(chboxC10);
        jPanel1.add(chboxC10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jLabel5.setText("Grado y Grupo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        lblGradoyGrupo.setFont(new java.awt.Font("Arial Black", 3, 12)); // NOI18N
        jPanel1.add(lblGradoyGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 155, 18));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo-ExamenDinamicogenerado.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
         int Dato=JOptionPane.showConfirmDialog(null,"¿Seguro que ha terminado de contestar\nsu examen?","Finalizar Examen",JOptionPane.YES_NO_OPTION);
       if (Dato==0)
       {
         if (chboxA1.isSelected())
       {
        punto1=datosrecuperados.a1+0;   
       }
      else if (chboxB1.isSelected())
       {
        punto3=datosrecuperados.b1+0;   
       }
      else if (chboxC1.isSelected())
       {
        punto3=datosrecuperados.c1+0;   
       }
       if (chboxA2.isSelected())
       {
        punto2=datosrecuperados.a2+0;   
       }
      else if (chboxB2.isSelected())
       {
        punto2=datosrecuperados.b2+0;   
       }
      else if (chboxC2.isSelected())
       {
        punto2=datosrecuperados.c2+0;   
       }
      
        if (chboxA3.isSelected())
       {
        punto3=datosrecuperados.a3+0;   
       }
      else if (chboxB3.isSelected())
       {
        punto3=datosrecuperados.b3+0;   
       }
      else if (chboxC3.isSelected())
       {
        punto3=datosrecuperados.c3+0;   
       }
        if (chboxA4.isSelected())
       {
        punto4=datosrecuperados.a4+0;   
       }
      else if (chboxB4.isSelected())
       {
        punto4=datosrecuperados.b4+0;   
       }
      else if (chboxC4.isSelected())
       {
        punto4=datosrecuperados.c4+0;   
       }
        if (chboxA5.isSelected())
       {
        punto5=datosrecuperados.a5+0;   
       }
      else if (chboxB5.isSelected())
       {
        punto5=datosrecuperados.b5+0;   
       }
      else if (chboxC5.isSelected())
       {
        punto5=datosrecuperados.c5+0;   
       }
      if (chboxA6.isSelected())
       {
        punto6=datosrecuperados.a6+0;   
       }
      else if (chboxB6.isSelected())
       {
        punto6=datosrecuperados.b6+0;   
       }
      else if (chboxC6.isSelected())
       {
        punto6=datosrecuperados.c6+0;   
       }
       if (chboxA7.isSelected())
       {
        punto7=datosrecuperados.a7+0;   
       }
      else if (chboxB7.isSelected())
       {
        punto7=datosrecuperados.b7+0;   
       }
      else if (chboxC7.isSelected())
       {
        punto7=datosrecuperados.c7+0;   
       }
       if (chboxA8.isSelected())
       {
        punto8=datosrecuperados.a8+0;   
       }
      else if (chboxB8.isSelected())
       {
        punto8=datosrecuperados.b8+0;   
       }
      else if (chboxC8.isSelected())
       {
        punto8=datosrecuperados.c8+0;   
       }
        if (chboxA9.isSelected())
       {
        punto9=datosrecuperados.a9+0;   
       }
      else if (chboxB9.isSelected())
       {
        punto9=datosrecuperados.b9+0;   
       }
      else if (chboxC9.isSelected())
       {
        punto9=datosrecuperados.c9+0;   
       }
        if (chboxA10.isSelected())
       {
        punto10=datosrecuperados.a10+0;   
       }
      else if (chboxB10.isSelected())
       {
        punto10=datosrecuperados.b10+0;   
       }
      else if (chboxC10.isSelected())
       {
        punto10=datosrecuperados.c10+0;   
       }
       totalAciertos=punto1+punto2+punto3+punto4+punto5+punto6+punto7+punto8+punto9+punto10;
       Promedio=(totalAciertos/10)*100;
         total=(int)Promedio;
       
         
         frmResultadosExamengenerado verfrmExamengenerado=new frmResultadosExamengenerado();
         verfrmExamengenerado.setVisible(true);
         this.hide();}
       
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        frmDatosdocente verfrmDatosdocente=new frmDatosdocente();
        verfrmDatosdocente.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmExamenDinamicoGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmExamenDinamicoGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmExamenDinamicoGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmExamenDinamicoGenerado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmExamenDinamicoGenerado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup13;
    private javax.swing.ButtonGroup buttonGroup14;
    private javax.swing.ButtonGroup buttonGroup15;
    private javax.swing.ButtonGroup buttonGroup16;
    private javax.swing.ButtonGroup buttonGroup17;
    private javax.swing.ButtonGroup buttonGroup18;
    private javax.swing.ButtonGroup buttonGroup19;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup20;
    private javax.swing.ButtonGroup buttonGroup21;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JRadioButton chboxA1;
    private javax.swing.JRadioButton chboxA10;
    private javax.swing.JRadioButton chboxA2;
    private javax.swing.JRadioButton chboxA3;
    private javax.swing.JRadioButton chboxA4;
    private javax.swing.JRadioButton chboxA5;
    private javax.swing.JRadioButton chboxA6;
    private javax.swing.JRadioButton chboxA7;
    private javax.swing.JRadioButton chboxA8;
    private javax.swing.JRadioButton chboxA9;
    private javax.swing.JRadioButton chboxB1;
    private javax.swing.JRadioButton chboxB10;
    private javax.swing.JRadioButton chboxB2;
    private javax.swing.JRadioButton chboxB3;
    private javax.swing.JRadioButton chboxB4;
    private javax.swing.JRadioButton chboxB5;
    private javax.swing.JRadioButton chboxB6;
    private javax.swing.JRadioButton chboxB7;
    private javax.swing.JRadioButton chboxB8;
    private javax.swing.JRadioButton chboxB9;
    private javax.swing.JRadioButton chboxC1;
    private javax.swing.JRadioButton chboxC10;
    private javax.swing.JRadioButton chboxC2;
    private javax.swing.JRadioButton chboxC3;
    private javax.swing.JRadioButton chboxC4;
    private javax.swing.JRadioButton chboxC5;
    private javax.swing.JRadioButton chboxC6;
    private javax.swing.JRadioButton chboxC7;
    private javax.swing.JRadioButton chboxC8;
    private javax.swing.JRadioButton chboxC9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAlumno;
    private javax.swing.JLabel lblEscuela;
    private javax.swing.JLabel lblGradoyGrupo;
    private javax.swing.JLabel lblMateria;
    private javax.swing.JLabel lblNombreDocente;
    private javax.swing.JLabel lblPregunta1;
    private javax.swing.JLabel lblPregunta10;
    private javax.swing.JLabel lblPregunta2;
    private javax.swing.JLabel lblPregunta3;
    private javax.swing.JLabel lblPregunta4;
    private javax.swing.JLabel lblPregunta5;
    private javax.swing.JLabel lblPregunta6;
    private javax.swing.JLabel lblPregunta7;
    private javax.swing.JLabel lblPregunta8;
    private javax.swing.JLabel lblPregunta9;
    // End of variables declaration//GEN-END:variables
}
