/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosProyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frmExamen extends javax.swing.JFrame {
    public static  String Pregunta[];
    public static int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0;
    int p1=1,p2=1,p3=1,p4=1,p5=1,p6=1,p7=1,p8=1,p9=1;
    float resultado=0;
    

    /**
     * Creates new form frmExamen
     */
    public frmExamen() {
        initComponents();
        this.setLocationRelativeTo(null);
        frmDatosalumno dato=new frmDatosalumno();
        lblUsuario.setText(dato.Nombre);
        lblEscuela.setText(dato.Escuela);
        lblGradoyGrupo.setText(dato.GrupoyGrado);
    }
     public static float Promedio=0;
     public static int total=0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        label1 = new java.awt.Label();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblp7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblEscuela = new javax.swing.JLabel();
        lblGradoyGrupo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jrbp5b = new javax.swing.JRadioButton();
        jrbp5a = new javax.swing.JRadioButton();
        jrbp1a = new javax.swing.JRadioButton();
        jrbp1b = new javax.swing.JRadioButton();
        jrbp1c = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        lblp2 = new javax.swing.JLabel();
        jrbp2a = new javax.swing.JRadioButton();
        jrbp2b = new javax.swing.JRadioButton();
        jrbp2c = new javax.swing.JRadioButton();
        lblp3 = new javax.swing.JLabel();
        jrbp3a = new javax.swing.JRadioButton();
        jrbp3b = new javax.swing.JRadioButton();
        jrbp3c = new javax.swing.JRadioButton();
        lblp4 = new javax.swing.JLabel();
        jrbp7a = new javax.swing.JRadioButton();
        jrbp7b = new javax.swing.JRadioButton();
        jrbp7c = new javax.swing.JRadioButton();
        lblp5 = new javax.swing.JLabel();
        jrbp4a = new javax.swing.JRadioButton();
        jrbp4b = new javax.swing.JRadioButton();
        jrbp4c = new javax.swing.JRadioButton();
        lblp6 = new javax.swing.JLabel();
        jrbp6a = new javax.swing.JRadioButton();
        jrbp6b = new javax.swing.JRadioButton();
        jrbp6c = new javax.swing.JRadioButton();
        lblp1 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        separador = new javax.swing.JLabel();
        lblp8 = new javax.swing.JLabel();
        lblp9 = new javax.swing.JLabel();
        jrbp8a = new javax.swing.JRadioButton();
        jrbp8b = new javax.swing.JRadioButton();
        jrbp8c = new javax.swing.JRadioButton();
        jrbp9a = new javax.swing.JRadioButton();
        jrbp9b = new javax.swing.JRadioButton();
        jrbp9c = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 3, 14)); // NOI18N
        jLabel7.setText(" EXAMEN CULTURAS MESOAMERICANAS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        lblp7.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp7.setText("7.-¿Cual cultura se caracterizo por realizar el culto a los muertos?");
        jPanel1.add(lblp7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 510, 20));

        jLabel6.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel6.setText("Escuela:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel4.setText("Grado y Grupo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, 20));

        lblUsuario.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 190, 20));

        lblEscuela.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jPanel1.add(lblEscuela, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 150, 20));

        lblGradoyGrupo.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jPanel1.add(lblGradoyGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 70, 20));

        jLabel8.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel8.setText("Alumno:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        buttonGroup5.add(jrbp5b);
        jrbp5b.setText("b)Falso");
        jPanel1.add(jrbp5b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        buttonGroup5.add(jrbp5a);
        jrbp5a.setText("a)Verdadero");
        jPanel1.add(jrbp5a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        buttonGroup1.add(jrbp1a);
        jrbp1a.setText("a)Los sacrificios");
        jrbp1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbp1aActionPerformed(evt);
            }
        });
        jPanel1.add(jrbp1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        buttonGroup1.add(jrbp1b);
        jrbp1b.setText("b) La mineria");
        jPanel1.add(jrbp1b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        buttonGroup1.add(jrbp1c);
        jrbp1c.setText("c) La agricultura");
        jPanel1.add(jrbp1c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel9.setText("Seleccione el inciso de acuerdo a la preguntas,cuando finalice el examen  Oprima en finalizar examen");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 570, 20));

        lblp2.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp2.setText("2.-¿A que cultura pertenece el centro ceremonial de Chichen Itza?");
        jPanel1.add(lblp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 470, 20));

        buttonGroup2.add(jrbp2a);
        jrbp2a.setText("a)Mayas");
        jPanel1.add(jrbp2a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        buttonGroup2.add(jrbp2b);
        jrbp2b.setText("b) Aztecas");
        jPanel1.add(jrbp2b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        buttonGroup2.add(jrbp2c);
        jrbp2c.setText("c)Toltecas");
        jPanel1.add(jrbp2c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        lblp3.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp3.setText("3.- ¿Cual era el tipo de religion  de las culturas Mesoamericanas?");
        jPanel1.add(lblp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 510, 20));

        buttonGroup3.add(jrbp3a);
        jrbp3a.setText("a) Politeismo");
        jPanel1.add(jrbp3a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        buttonGroup3.add(jrbp3b);
        jrbp3b.setText("b)Monoteismo");
        jPanel1.add(jrbp3b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        buttonGroup3.add(jrbp3c);
        jrbp3c.setText("c)Induismo");
        jPanel1.add(jrbp3c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));

        lblp4.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp4.setText("4.-¿Como se llama el alimento que elaboraban los Aztecas mas pobres y que consistia en hacer sobres de maiz?");
        jPanel1.add(lblp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 630, 20));

        buttonGroup7.add(jrbp7a);
        jrbp7a.setText("a) Toltecas");
        jPanel1.add(jrbp7a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        buttonGroup7.add(jrbp7b);
        jrbp7b.setText("b)Zapotecas");
        jPanel1.add(jrbp7b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        buttonGroup7.add(jrbp7c);
        jrbp7c.setText("c)Mixtecos");
        jPanel1.add(jrbp7c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, -1, -1));

        lblp5.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp5.setText("5.-¿La religion Politeista consiste en tener mas de un Dios?");
        jPanel1.add(lblp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 510, 20));

        buttonGroup4.add(jrbp4a);
        jrbp4a.setText("b)Tortas");
        jPanel1.add(jrbp4a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        buttonGroup4.add(jrbp4b);
        jrbp4b.setText("b)Tortilla");
        jPanel1.add(jrbp4b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        buttonGroup4.add(jrbp4c);
        jrbp4c.setText("c)Tamales");
        jPanel1.add(jrbp4c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        lblp6.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp6.setText("6.- ¿Como se llamo la cultura que creo el juego de Pelota Mesoamericano?");
        jPanel1.add(lblp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 510, 20));

        buttonGroup6.add(jrbp6a);
        jrbp6a.setText("a)Cultura Tolteca");
        jPanel1.add(jrbp6a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        buttonGroup6.add(jrbp6b);
        jrbp6b.setText("b)Cultura Olmeca");
        jPanel1.add(jrbp6b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        buttonGroup6.add(jrbp6c);
        jrbp6c.setText("c)Cultura Zapoteca");
        jPanel1.add(jrbp6c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        lblp1.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp1.setText("1.- ¿Cual fue el principal base de economia de los olmecas?");
        jPanel1.add(lblp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 470, 20));

        btnSalir.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 0), new java.awt.Color(0, 204, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 50, 20));

        btnFinalizar.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnFinalizar.setText("Finalizar examen");
        btnFinalizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 0), new java.awt.Color(0, 204, 0), new java.awt.Color(0, 51, 51), new java.awt.Color(0, 51, 51)));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 130, 20));

        separador.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        separador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComplementoImagenExamen-1.png"))); // NOI18N
        jPanel1.add(separador, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 90, 650, 20));

        lblp8.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp8.setText("8-¿Que tipo de Guerreros eran los Toltecas?");
        jPanel1.add(lblp8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 510, 20));

        lblp9.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        lblp9.setText("9.-¿Como se llamo la cultura que domestico por primera ves el Maiz?");
        jPanel1.add(lblp9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 510, 20));

        buttonGroup8.add(jrbp8a);
        jrbp8a.setText("a)Guerreros religiosos");
        jPanel1.add(jrbp8a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        buttonGroup8.add(jrbp8b);
        jrbp8b.setText("b)Guerreros naturales");
        jPanel1.add(jrbp8b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        buttonGroup8.add(jrbp8c);
        jrbp8c.setText("c)Guerreros Apocalipticos");
        jPanel1.add(jrbp8c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, -1, -1));

        buttonGroup9.add(jrbp9a);
        jrbp9a.setText("a)Cultura Azteca");
        jPanel1.add(jrbp9a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, -1, -1));

        buttonGroup9.add(jrbp9b);
        jrbp9b.setText("b)Cultura Olmeca");
        jPanel1.add(jrbp9b, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 570, -1, -1));

        buttonGroup9.add(jrbp9c);
        jrbp9c.setText("c)Cultura Teotihuacana");
        jPanel1.add(jrbp9c, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ImagenExamen.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // TODO add your handling code here:
        Pregunta= new String [9];
        Pregunta [0]=lblp1.getText();
        Pregunta [1]=lblp2.getText();
        Pregunta [2]=lblp3.getText();
        Pregunta [3]=lblp4.getText();
        Pregunta [4]=lblp5.getText();
        Pregunta [5]=lblp6.getText();
        Pregunta [6]=lblp7.getText();
        Pregunta [7]=lblp8.getText();
        Pregunta [8]=lblp9.getText();
        if(jrbp1c.isSelected())
        {
            r1=p1;
            if(jrbp1a.isSelected()||jrbp1b.isSelected())
            {
            r1=0;   
            }
        }
         if(jrbp2a.isSelected())
        {
            r2=p2;
            if(jrbp2b.isSelected()||jrbp2c.isSelected())
            {
             r2=0;   
            }
        }
          if(jrbp3a.isSelected())
        {
            
            r3=p3;
            if(jrbp3b.isSelected()||jrbp3c.isSelected())
            {
             r3=0;   
            }
        }
          if(jrbp4c.isSelected())
        {
            r4=p4;
            if(jrbp4a.isSelected()||jrbp4b.isSelected())
            {
             r4=0;   
            }
        }
          if(jrbp5a.isSelected())
        {
            r5=p5;
            if(jrbp5b.isSelected())
            {
             r5=0;   
            }
        }
          if(jrbp6b.isSelected())
        {
            r6=p6;
            if(jrbp6a.isSelected()||jrbp6c.isSelected())
            {
             r6=0;   
            }
        }
          if(jrbp7b.isSelected())
        {
            r7=p7;
            if(jrbp7a.isSelected()||jrbp7c.isSelected())
            {
             r7=0;   
            }
        }
            if(jrbp8a.isSelected())
        {
            r8=p8;
            if(jrbp8b.isSelected()||jrbp8c.isSelected())
            {
             r8=0;   
            }
        }
            if(jrbp9c.isSelected())
        {
            r9=p9;
            if(jrbp9a.isSelected()||jrbp9b.isSelected())
            {
             r9=0;   
            }
        }
        
        int Dato=JOptionPane.showConfirmDialog(null,"¿Seguro que ha terminado de contestar\nsu examen?","Finalizar Examen",JOptionPane.YES_NO_OPTION);
        if(Dato==0)
        {
         resultado=r1+r2+r3+r4+r5+r6+r7+r8+r9;  
        Promedio=(resultado/9)*100;
         total=(int)Promedio;
        
        frmResultadoexamen verfrmResultadoexamen=new frmResultadoexamen();
        verfrmResultadoexamen.setVisible(true);
        this.hide();   
        }
        
        
        
        
    
        
       

    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void jrbp1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbp1aActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jrbp1aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbp1a;
    private javax.swing.JRadioButton jrbp1b;
    private javax.swing.JRadioButton jrbp1c;
    private javax.swing.JRadioButton jrbp2a;
    private javax.swing.JRadioButton jrbp2b;
    private javax.swing.JRadioButton jrbp2c;
    private javax.swing.JRadioButton jrbp3a;
    private javax.swing.JRadioButton jrbp3b;
    private javax.swing.JRadioButton jrbp3c;
    private javax.swing.JRadioButton jrbp4a;
    private javax.swing.JRadioButton jrbp4b;
    private javax.swing.JRadioButton jrbp4c;
    private javax.swing.JRadioButton jrbp5a;
    private javax.swing.JRadioButton jrbp5b;
    private javax.swing.JRadioButton jrbp6a;
    private javax.swing.JRadioButton jrbp6b;
    private javax.swing.JRadioButton jrbp6c;
    private javax.swing.JRadioButton jrbp7a;
    private javax.swing.JRadioButton jrbp7b;
    private javax.swing.JRadioButton jrbp7c;
    private javax.swing.JRadioButton jrbp8a;
    private javax.swing.JRadioButton jrbp8b;
    private javax.swing.JRadioButton jrbp8c;
    private javax.swing.JRadioButton jrbp9a;
    private javax.swing.JRadioButton jrbp9b;
    private javax.swing.JRadioButton jrbp9c;
    private java.awt.Label label1;
    private javax.swing.JLabel lblEscuela;
    private javax.swing.JLabel lblGradoyGrupo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblp1;
    private javax.swing.JLabel lblp2;
    private javax.swing.JLabel lblp3;
    private javax.swing.JLabel lblp4;
    private javax.swing.JLabel lblp5;
    private javax.swing.JLabel lblp6;
    private javax.swing.JLabel lblp7;
    private javax.swing.JLabel lblp8;
    private javax.swing.JLabel lblp9;
    private javax.swing.JLabel separador;
    // End of variables declaration//GEN-END:variables
}
