/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulariosProyecto;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import java.applet.AudioClip;

/**
 *
 * @author Usuario
 */
public class frmPreexamen extends javax.swing.JFrame {
    int datoAudio=1;
    
    

    /**
     * Creates new form frmPreexamen
     */
    public frmPreexamen() {
        initComponents();
        this.setLocationRelativeTo(null);
        txaInfo.setLineWrap(true);
        txaInfo.setWrapStyleWord(true);
        txaInfo.setText("");
        lblTitulo_culltura.setText("Cultura Olmeca");
        lblAño.setText("1500 a.C - 100 d.C");
        btnOlmeca.setBackground(Color.green);
        btnReproducir.setVisible(false);
        btnReproducir.disable();
 txaInfo.setText("Ubicacion geografica:Se establecio en lo que hoy es el sur  del  estado "
               + "de Veracruz  y  noroeste  de  Tabasco  principalmente. "
           + "\n\nPrincipales centros  historicos: La  civilizacion  Olmeca se constituyo "
               + "principalmente   alrededor   de   3 centros  ceremoniales   los  cuales "
               + "eran:San Lorenzo,la Venta y Tres Zapotes."
           + "\n\nFormas  economica  de  sutentabilidad: La economia de  los Olmecas  fue "
               + "basada principalmente  en   los  productos  agricolas  que  comerciaban "
               + " entre ellos tanto como de pueblos vecinos."
           + "\n\nSus 3 principales dioses: Jaguar(Nahual):Fue  su principal dios  y  fue "
               + "representado innumerabemente en arte lapidario.\n"
               + "Dragon Olmeca: Se sabe que antes de la serpiente emplumada y se  hacian "
               + "rituales dedicados a esta deidad.\n"
               + "Serpiente Emplumada:Era uno  de  los dioses principales  y estaba  bien "
               + "relacionado con la vida y el viento."
           + "\n\nTipo de religion: La  religión era politeísta creian  en  la existencia "
               + "de una gran cantidad de dioses.Las fuentes en este aspecto son limitadas "
               + "aunque conocemos a varios dioses olmecas se   supone   que   existieron  "
               + "siendo los más importantes de aquellos los que tenemos conocimiento.");
        lblFoto1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\olmeca.jpg"));
            lblFoto2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\olmeca2.jpg"));
             
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInfo = new javax.swing.JTextArea();
        lblFoto2 = new javax.swing.JLabel();
        lblFoto1 = new javax.swing.JLabel();
        btnRealizarexamen = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        btnOlmeca = new javax.swing.JButton();
        btnZapotecas = new javax.swing.JButton();
        btnMixtecas = new javax.swing.JButton();
        btnToltecas = new javax.swing.JButton();
        btnAztecas = new javax.swing.JButton();
        btnTeotihuacanos = new javax.swing.JButton();
        btnMayas = new javax.swing.JButton();
        Recuadro = new javax.swing.JLabel();
        lblTitulo_culltura = new javax.swing.JLabel();
        lblAño = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        btnReproducir = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txaInfo.setColumns(20);
        txaInfo.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        txaInfo.setRows(5);
        txaInfo.setBorder(null);
        jScrollPane1.setViewportView(txaInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 400, 370));
        getContentPane().add(lblFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 160, 130));
        getContentPane().add(lblFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 160, 130));

        btnRealizarexamen.setBackground(new java.awt.Color(255, 255, 255));
        btnRealizarexamen.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnRealizarexamen.setText("Realizar Memorama");
        btnRealizarexamen.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.green, java.awt.Color.green));
        btnRealizarexamen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarexamenActionPerformed(evt);
            }
        });
        getContentPane().add(btnRealizarexamen, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 560, 180, 40));

        btnAtras.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.green, java.awt.Color.green));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 50, 20));

        btnSalir1.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnSalir1.setText("Salir");
        btnSalir1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.green, java.awt.Color.green));
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 630, 50, 20));

        btnOlmeca.setBackground(new java.awt.Color(255, 255, 255));
        btnOlmeca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnOlmeca.setText("Olmecas");
        btnOlmeca.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnOlmeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlmecaActionPerformed(evt);
            }
        });
        getContentPane().add(btnOlmeca, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 140, 70));

        btnZapotecas.setBackground(new java.awt.Color(255, 255, 255));
        btnZapotecas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnZapotecas.setText("Zapotecas");
        btnZapotecas.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnZapotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZapotecasActionPerformed(evt);
            }
        });
        getContentPane().add(btnZapotecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 140, 80));

        btnMixtecas.setBackground(new java.awt.Color(255, 255, 255));
        btnMixtecas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMixtecas.setText("Mixtecas");
        btnMixtecas.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnMixtecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMixtecasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMixtecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 140, 80));

        btnToltecas.setBackground(new java.awt.Color(255, 255, 255));
        btnToltecas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnToltecas.setText("Toltecas");
        btnToltecas.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnToltecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToltecasActionPerformed(evt);
            }
        });
        getContentPane().add(btnToltecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 140, 80));

        btnAztecas.setBackground(new java.awt.Color(255, 255, 255));
        btnAztecas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAztecas.setText("Aztecas");
        btnAztecas.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnAztecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAztecasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAztecas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 140, 80));

        btnTeotihuacanos.setBackground(new java.awt.Color(255, 255, 255));
        btnTeotihuacanos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnTeotihuacanos.setText("Teotihuacanos");
        btnTeotihuacanos.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnTeotihuacanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeotihuacanosActionPerformed(evt);
            }
        });
        getContentPane().add(btnTeotihuacanos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 280, 140, 80));

        btnMayas.setBackground(new java.awt.Color(255, 255, 255));
        btnMayas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMayas.setText("Mayas");
        btnMayas.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        btnMayas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayasActionPerformed(evt);
            }
        });
        getContentPane().add(btnMayas, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 200, 140, 80));

        Recuadro.setBackground(new java.awt.Color(0, 0, 255));
        Recuadro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComplementoPreexamen-V.png"))); // NOI18N
        getContentPane().add(Recuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 420, 390));

        lblTitulo_culltura.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblTitulo_culltura.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblTitulo_culltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 310, 40));

        lblAño.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        lblAño.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lblAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 310, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoPreexamen.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 650));

        btnReproducir.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        btnReproducir.setText("Click aqui para reproducir audio lectura");
        btnReproducir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.red, java.awt.Color.red, java.awt.Color.green, java.awt.Color.green));
        btnReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirActionPerformed(evt);
            }
        });
        getContentPane().add(btnReproducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 340, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRealizarexamenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarexamenActionPerformed
        // TODO add your handling code here:
        frmCulturasdinamicas verCulturasdinamicas=new frmCulturasdinamicas();
        verCulturasdinamicas.setVisible(true);
        this.hide();
        

    }//GEN-LAST:event_btnRealizarexamenActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        // TODO add your handling code here:
        frmSeleccion verfrmSeleccion=new frmSeleccion();
        verfrmSeleccion.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    private void btnOlmecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlmecaActionPerformed
        // TODO add your handling code here
        datoAudio=1;
        lblTitulo_culltura.setText("Cultura Olmeca");
        lblAño.setText("1500 a.C - 100 d.C");
        btnOlmeca.setBackground(Color.green);
        btnZapotecas.setBackground(Color.WHITE);
        btnAztecas.setBackground(Color.WHITE);
        btnMayas.setBackground(Color.WHITE);
        btnTeotihuacanos.setBackground(Color.WHITE);
        btnToltecas.setBackground(Color.WHITE);
        btnMixtecas.setBackground(Color.WHITE);
        txaInfo.setText("Ubicacion geografica:Se establecio en lo que hoy es el sur del "
               + "estado de Veracruz y noroeste de Tabasco principalmente. "
               + "\n\nPrincipales centros historicos:La civilizacion Olmeca se constituyo "
               + "principalmente alrededor de 3 centros ceremoniales los cuales: "
               + "eran:San Lorenzo,la Venta y Tres Zapotes."
               + "\n\nForma economica de sutentabilidad: La economia de los Olmecas fue "
               + "basada principalmente en los productos agricolas que comerciaban "
               + " entre ellos tanto como de pueblos vecinos."
               + "\n\nSus 3 principales dioses: Jaguar(Nahual):Fue su principal dios y fue "
               + "representado innumerabemente en arte lapidario.\n"
               + "Dragon Olmeca: Se sabe que antes de la serpiente emplumada "
               + "se hacian rituales dedicados a esta deidad \n"
               + "Serpiente Emplumada:Era uno de los dioses principales y estaba "
               + "relacionado con la vida y el viento."
               + "\n\nTipo de religion:La religión era politeísta, creyendo en la existencia de "
               + "una gran cantidad de dioses. Las fuentes en este aspecto son limitadas "
               + "aunque conocemos a varios dioses olmecas se supone que existieron "
               + "siendo los más importantes de aquellos los que tenemos conocimiento.");
        lblFoto1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\olmeca.jpg"));
            lblFoto2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\olmeca2.jpg"));
    }//GEN-LAST:event_btnOlmecaActionPerformed

    private void btnZapotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZapotecasActionPerformed
        // TODO add your handling code here:
        datoAudio=2;
        lblTitulo_culltura.setText("Cultura Zapoteca");
        lblAño.setText("500 a.C - 950 d.C");
        btnOlmeca.setBackground(Color.WHITE);
        btnZapotecas.setBackground(Color.green);
        btnAztecas.setBackground(Color.WHITE);
        btnMayas.setBackground(Color.WHITE);
        btnTeotihuacanos.setBackground(Color.WHITE);
        btnToltecas.setBackground(Color.WHITE);
        btnMixtecas.setBackground(Color.WHITE);
        txaInfo.setText("Ubicacion geografica: Los Zapotecas habitaron principalmente en el "
                + "Istmo de Tehuantepec ubicado al suroeste del estado de Oaxaca "
                + "su poblacion se concentro en Juchitan y Tehuantepec."
                + "\n\nPrincipales centros historicos: Los sitios mas importantes de "
                + "la cultura Zapoteca fueron Mitla,Huijazoo,Lambityeco y Zaachila "
                + "durante el periodo de asentamiento de los Zapotecas."
                + "\n\nForma economica de sutentabilidad: Los Zapotecas desarrollaron "
                + "una agricultura muy variada tal es el caso de varias especies "
                + "de chile,frijol,calabaza y maiz que servia de sustento para "
                + "numerosas aldeas."
                + "\n\nSus 3 principales dioses:Xipe Totec: Representaba la vida y la muerte "
                + "ademas de la resurreccion,el era considerado su principal dios.\n"
                + "Pitao Cocijo: Era el dios del trueno y de la lluvia y "
                + "fue venerado y temido por los primeros Zapotecas que existieron\n."
                + "Pitao Cozobi: Representaba al maiz ,y lo consideraban como "
                + "el dios del bien de la abundancia Naturalmente ante siembras "
                + "de cultivos."
                + "\n\nTipo de religion: El tipo de religion de los Zapotecas era "
                + "Politeista ya que creian en muchos dioses los cuales relacionaban "
                + "y adoraban tanto como a los medios naturales.");
        lblFoto1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\zapoteca.jpg"));
            lblFoto2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\zapoteca2.jpg"));
    }//GEN-LAST:event_btnZapotecasActionPerformed

    private void btnMayasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayasActionPerformed
        // TODO add your handling code here:
        datoAudio=3;
        lblTitulo_culltura.setText("Cultura Maya");
        lblAño.setText("2000 a.C - 250 d.C");
        btnOlmeca.setBackground(Color.WHITE);
        btnZapotecas.setBackground(Color.WHITE);
        btnAztecas.setBackground(Color.WHITE);
        btnMayas.setBackground(Color.green);
        btnTeotihuacanos.setBackground(Color.WHITE);
        btnToltecas.setBackground(Color.WHITE);
        btnMixtecas.setBackground(Color.WHITE);
        txaInfo.setText("Ubicacion geografica: La cultura maya se extendio en la superficie "
                + "que abarca el sur de Mexico,Belice,Guatemala y parte de "
                + "Honduras."
               + "\n\nPrincipales centros historicos: En la actualidad se conocen muchos "
                + "sitios arqueologicos pertenecientes a la cultura Maya "
                + "los cuales son: Palenque,Calakmul,Uxmal y Chichen Itza."
               + "\n\nFormas economica de sutentabilidad: La agricultura del maiz formo "
                + "la columna vertebral de la economia Maya la cual empleo el sistema "
                + "de milpa que consistia en el cultivo intensivo y rotativo de "
                + "empobrecidos suelos selvaticos."
               + "\n\nSus 3 principales dioses: Hunab Ku: Era considerado el padre "
                + "de todos los dioses y cuyo nombre significa un solo Dios.\n"
                + "Itzamna: Conocido como el soberano del cielo,el verdadero "
                + "amo del dia y de la noche cuya representacion era "
                + "un dragon alado de 2 cabezas.\n"
                + "Chaac: Este dios era considerado el padre de los relampagos "
                + "y de la lluvia ademas de que fue uno de los mas alabados en "
                + "el panteon maya."
               + "\n\nTipo de religion: Los mayas eran Politeistas,ya que adoraban a "
                + "diferentes dioses relacionados con la naturaleza.");
        lblFoto1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\maya.jpg"));
            lblFoto2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\maya2.jpg"));
            
    }//GEN-LAST:event_btnMayasActionPerformed

    private void btnTeotihuacanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeotihuacanosActionPerformed
        // TODO add your handling code here:
        datoAudio=4;
        lblTitulo_culltura.setText("Cultura Teotihuacana");
        lblAño.setText("200 a.C - 900 d.C");
        btnOlmeca.setBackground(Color.WHITE);
        btnZapotecas.setBackground(Color.WHITE);
        btnAztecas.setBackground(Color.WHITE);
        btnMayas.setBackground(Color.WHITE);
        btnTeotihuacanos.setBackground(Color.green);
        btnToltecas.setBackground(Color.WHITE);
        btnMixtecas.setBackground(Color.WHITE);
        txaInfo.setText("Ubicacion geografica:  La cultura Teotihuacana se establecio en "
                + "el Altiplano central de Mexico Actualmente los municipios "
                + "de las piramides y Teotihuacan del estado de Mexico."
               + "\n\nPrincipales centros historicos: La mayor parte de edificios "
                + "que conocemos integraron Teotihuacan tal es el caso de "
                + "las piramides del Sol y la Luna,El Templo de Quetzalcoatl "
                + "o el templo de los Jaguares."
               + "\n\nFormas economica de sutentabilidad: De acuerdo con los registros "
                + "arqueologicos la cultura Teotihuacana se baso principalmente "
                + "de la agricultura ademas de el comercio y el tributo."
               + "\n\nSus 3 principales dioses: Quetzalcoatl: Tambien conocido como la "
                + "Serpiente emplumada,es su dios principal y representa la "
                + "dualidad del Hombre.\n"
                + "Chalchiuhtlicue: Esta diosa era asociada con la fertilidad, "
                + "y se representaba con grandes orejeras,un poncho y "
                + "una falda de jade con estampados geometricos.\n"
                + "Huehueteotl: Era el dios del fuego y esta representado por "
                + "un anciano desdentado,barbudo,arrugado y jorobado."
               + "\n\nTipo de religion: Los Teotihuacanos creian en mas de un solo dios "
                + "es decir profesaban una religion Politeista y asociada a lo natural.");
        lblFoto1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\teotihuacano.jpg"));
            lblFoto2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\teotihuacano2.jpg"));
    }//GEN-LAST:event_btnTeotihuacanosActionPerformed

    private void btnMixtecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMixtecasActionPerformed
        // TODO add your handling code here:
        datoAudio=5;
        lblTitulo_culltura.setText("Cultura Mixteca");
        lblAño.setText("1500 a.C - 1523 d.C");
        btnOlmeca.setBackground(Color.WHITE);
        btnZapotecas.setBackground(Color.WHITE);
        btnAztecas.setBackground(Color.WHITE);
        btnMayas.setBackground(Color.WHITE);
        btnTeotihuacanos.setBackground(Color.WHITE);
        btnToltecas.setBackground(Color.WHITE);
        btnMixtecas.setBackground(Color.green);
        txaInfo.setText("Ubicacion geografica: La cultura Mixteca abarco principalmente "
                + "los estados de Guerrero y Puebla ademas de que en mayor proporcion "
                + "el estado de Oaxaca."
               + "\n\nPrincipales centros historicos: Entre los principales centros "
                + "ceremoniales de los Mixtecas se encuentran Monte Alban,Mitla y  "
                + "Teotihuacan."
               + "\n\nFormas economica de sutentabilidad: La mayoria de los pueblos "
                + "se sustentaban en mayor parte de la agricultura en las regiones "
                + "donde el clima lo permitia."
               + "\n\nSus 3 principales dioses: Dzahui: Es el nombre de el dios de la "
                + "lluvia de la cultura Mixteca propiamente traducido al español "
                + "como lluvia.\n"
                + "Cohuy: Es considerado como el dios del maiz,alimento sagrado "
                + "para ellos y protector de sus cosechas.\n"
                + "Huehueteotl: Es el dios del fuego ,principal elemento natural "
                + "considerado por los Mixtecos."
               + "\n\nTipo de religion: Contaban con la creencia hacia muchos dioses "
                + "y deidades asignados para los distintos tipos de naturaleza.");
        lblFoto1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\mixteca.jpg"));
            lblFoto2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\mixteca2.jpg"));
    }//GEN-LAST:event_btnMixtecasActionPerformed

    private void btnAztecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAztecasActionPerformed
        // TODO add your handling code here:
        datoAudio=6;
        lblTitulo_culltura.setText("Cultura Azteca");
        lblAño.setText("1345 d.C -1521 d.C");
        btnOlmeca.setBackground(Color.WHITE);
        btnZapotecas.setBackground(Color.WHITE);
        btnAztecas.setBackground(Color.green);
        btnMayas.setBackground(Color.WHITE);
        btnTeotihuacanos.setBackground(Color.WHITE);
        btnToltecas.setBackground(Color.WHITE);
        btnMixtecas.setBackground(Color.WHITE);
        txaInfo.setText("Ubicacion geografica: La cultura Azteca se ubico al norte de el "
                + "area Mesoamericana es decir el actual norte de Mexico."
               + "\n\nPrincipales centros historicos: Los Aztecas al tener una gran expansion "
                + "territorial contaban con muchos centros ceremoniales pero los "
                + "mas destacables eran Chapultepec,Templo Mayor y Tlatelolco."
               + "\n\nFormas economica de sutentabilidad: Consideraban la agricultura como "
                + "su principal actividad economica y llevaban a cabo esta actividad "
                + "en las Chinampas o islas artificiales."
               + "\n\nSus 3 principales dioses: Tlaloc: Es el dios Azteca de las lluvias y  "
                + "tormentas,asi como una de sus deidades mas antiguas de esta cultura\n"
                + "Huitzilopochtli: Era considerado el padre de los Aztecas ,Asi como "
                + "tambien es conocido como el dios mas poderoso de esta cultura "
                + "o el Padre de los Aztecas\n"
                + "Tezcatlipoca: Se le consideraba como  la contraposicion de Quetzalcoatl "
                + "el cual representaba lo desconocido y lo oscuro"
               + "\n\nTipo de religion: Creian en diferentes dioses por lo tanto su tipo de "
                + "religion fue Politeista y variada en cuanto a creencias.");
        lblFoto1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\azteca.jpg"));
            lblFoto2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\azteca2.jpg"));
    }//GEN-LAST:event_btnAztecasActionPerformed

    private void btnToltecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToltecasActionPerformed
        // TODO add your handling code here
        datoAudio=7;
        lblTitulo_culltura.setText("Cultura Tolteca");
        lblAño.setText("900 d.C - 1200 d.C");
        btnOlmeca.setBackground(Color.WHITE);
        btnZapotecas.setBackground(Color.WHITE);
        btnAztecas.setBackground(Color.WHITE);
        btnMayas.setBackground(Color.WHITE);
        btnTeotihuacanos.setBackground(Color.WHITE);
        btnToltecas.setBackground(Color.green);
        btnMixtecas.setBackground(Color.WHITE);
        txaInfo.setText("Ubicacion geografica: Los Toltecas se establecieron en la "
                + "Meseta central o bien en la zona que hoy abarcan los estados de "
                + "Tlaxcala,Hidalgo,Estado de Mexico,Morelos y Puebla"
               + "\n\nPrincipales centros historicos: Los principales recintos ceremoniales "
                + "de los Toltecas fueron templos superiores tal es el caso de Tula, "
                + "Tzompantli y Huacapalco."
               + "\n\nFormas economica de sutentabilidad: Se basaba en la agricultura de "
                + "extensos campos de cultivo integrados por complejos sistemas de  "
                + "canales."
               + "\n\nSus 3 principales dioses: Quetzalcoatl: Era un dios colmado de todo "
                + "tipo de principios espirituales y era conocido como Serpiente emplumada\n"
                + "Tezcatlipoca: Era la contraparte de Quetzalcoatl por ser un dios de "
                + "naturaleza guerrera y antagonista por terminos oscuros \n"
                + "Tlaloc: Correspondia al dios de la lluvia y de las aguas, por lo "
                + "tanto era indispensable su ayuda para cultivar la tierra y cosechar."
               + "\n\nTipo de religion: Su tipo de religion de los Toltecas fue Politeista"
                + "ya que creian en mas de un solo dios,cada dios desempeñaba un papel "
                + "importante para cada elemento y suceso natural que se les atribuia");
        lblFoto1.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\tolteca.jpg"));
            lblFoto2.setIcon(new ImageIcon("C:\\Users\\kenor\\Documents\\NetBeansProjects\\Proyecto_Integrador\\build\\classes\\ImagenesCulturas\\tolteca2.jpg"));
    }//GEN-LAST:event_btnToltecasActionPerformed

    private void btnReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirActionPerformed
        // TODO add your handling code here:
        //AudioClip SoundOl;
         //SoundOl= java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AudioOlmeca.wav"));
         //AudioClip SoundMa;
         //SoundMa= java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AudioMayas.wav"));
         //AudioClip SoundMi;
        // SoundMi= java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AudioMixtecos.wav"));
        // AudioClip SoundTe;
         //SoundTe= java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AudioTeotihuacanos.wav"));
         //AudioClip SoundTo;
         //SoundTo= java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AudioTolteca.wav"));
         //AudioClip SoundZa;
         //SoundZa= java.applet.Applet.newAudioClip(getClass().getResource("/Audios/AudioZapoteca.wav"));
        // AudioClip SoundAz;
         //SoundAz= java.applet.Applet.newAudioClip(getClass().getResource("/Audios/CulturaAzteca.wav"));
        //if (btnReproducir.isSelected())
        //{
         //btnReproducir.setText("Click Aqui para detener la Audio Lectura"); 
         //if(datoAudio==1)
         //{
          //   SoundOl.play();
  //       }
    //   else if(datoAudio==2)
    //     {
    //         SoundZa.play();
    //     }
    //     else if(datoAudio==3)
    //     {
    //         SoundMa.play();
    //     }
    //     else if(datoAudio==4)
    //     {
    //         SoundTe.play();
    //     }
    //     else if(datoAudio==5)
    //     {
    //         SoundMi.play();
    //     }
    //      else if(datoAudio==6)
    ////     {
    //         SoundAz.play();
    //     }
    //////
     //   else if(datoAudio==7)
       //  {
       //      SoundTo.play();
       //  }
       // }
       // else if(btnReproducir.isSelected()==false)
       // {
       // btnReproducir.setText("Click Aqui para reproducir la audio lectura");
       // SoundAz.stop();
       // SoundZa.stop();
       // SoundTo.stop();
       // SoundTe.stop();
       //// SoundMi.stop();
       //// SoundMa.stop();
       //// SoundOl.stop();
      
        
            
    }//GEN-LAST:event_btnReproducirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPreexamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPreexamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPreexamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPreexamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPreexamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Recuadro;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnAztecas;
    private javax.swing.JButton btnMayas;
    private javax.swing.JButton btnMixtecas;
    private javax.swing.JButton btnOlmeca;
    private javax.swing.JButton btnRealizarexamen;
    private javax.swing.JToggleButton btnReproducir;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JButton btnTeotihuacanos;
    private javax.swing.JButton btnToltecas;
    private javax.swing.JButton btnZapotecas;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAño;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblTitulo_culltura;
    private javax.swing.JTextArea txaInfo;
    // End of variables declaration//GEN-END:variables
}
